highlighter: rouge
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 4000
safe: true
url: http://biomadeira.github.io/vitae
author: Fábio Madeira

# edit this section with your information
# biomadeira.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: /
title: 左康生的个人简历
name: 左康生
email: zhen0578@qq.com
email_full: mailto:zhen0578@qq.com
#website: github.io/sustain
#website_full: https://biomadeira.github.io/sustain
github: https://github.com/waitkafuka
#twitter: twitter
tel: 18037226583
tel_full: tel:18037226583
address: 河南省郑州市花园路59号邮储大厦2101
postcode: 450000
city: 郑州
country: 中国
#google_analytics: UA-69300817-1

# needed for travis-ci build
exclude: [vendor]
